import Head from "next/head";
import styled from "@emotion/styled";
import cards from "@/assets/cardContent";
import Link from "next/link";

/** @jsxImportSource @emotion/react */
import { css, jsx } from "@emotion/react";

//Components
import Card from "@/components/Card";
import Button from "@/components/Button";
import CenterElementsContainer from "@/components/GeneralContainers/CenterElementsContainer";
import NextLink from "@/components/NextLink";
import Title1 from "@/components/Titles/Title1";

const tilesStyles = css`
  display: flex;
  flex-direction: column;
  margin: 0 50px;
  @media (min-width: 650px) {
    flex-direction: row;
    justify-content: space-between;
  }
`;

const subTextStyles = css`
text-align: center;
font-size: 16px;
margin-top: -20px;
  @media (min-width: 650px) {
    font-size: 22px;
  }
`;

const ArrowIcon = styled.i`
  font-size: 22px;
  height: 22px;
`;

const SectionContainer = styled(CenterElementsContainer)`
margin: 0 5%;
`


export default function Home() {
  return (
    <>
      <Head>
        <title>milia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Image
          src="https://images.pexels.com/photos/163185/old-retro-antique-vintage-163185.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
          alt=""
        /> */}
        <SectionContainer>
          <Title1>
            Explore new places, uncover hidden gems, marvel at natural wonders,
            or document your surveys. 
          </Title1>
          <p css={subTextStyles}>Never miss a moment – tag your experiences
            and curate your own unique stories.</p>
          <NextLink href="/login">
            <Button>
              Start recording{" "}
              <ArrowIcon className="fi fi-rr-arrow-small-right" />
            </Button>
          </NextLink>
        </SectionContainer>
        <section css={tilesStyles}>
          {cards.map(({ id, image, text }) => (
            <Card key={id} image={image} text={text} />
          ))}
        </section>
      </main>
    </>
  );
}
